# image: https://hub.docker.com/r/bitnami/suitecrm
# src: https://www.github.com/javanile/vtiger

version: '3.8'

services:

  vtiger:
    image: websoft9dev/vtiger:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_PORT}:80
    volumes:
      - vtiger:/var/www/html
    links:
      - mysql

  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-mysql
    environment:
      - MYSQL_DATABASE=${DB_MYSQL_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_MYSQL_PASSWORD}
      - MYSQL_USER=${DB_MYSQL_USER}
      - MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode=NO_ENGINE_SUBSTITUTION --local_infile=ON
    ports:
      - ${DB_MYSQL_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin:latest
      container_name: ${APP_NAME}-phpmyadmin
      environment:
       - UPLOAD_LIMIT=200M
       - PMA_ARBITRARY=1
      restart: always
      ports:
       - 9090:80

volumes:
  mysql:
  vtiger:

networks:
  default:
      name: ${APP_NAME}